---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-cflt-bike-rental
  namespace: demo-cflt-bike-rental
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: cflt-bike-rental
  serviceName: demo
  template:
    metadata:
      labels:
        demo: cflt-bike-rental
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: bike-rental-secret
            items:
              - key: secret.properties
                path: secret.properties
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          volumeMounts:
            - name: config-volume
              mountPath: secret.properties
              subPath: secret.properties
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
